server:
  port: 8379

spring:
  data:
    redis:
      client-type: ${REDIS_TYPE:LETTUCE}
      cluster:
        nodes: ${REDIS_NODE:redis-cluster.redis.svc.cluster.local:6379}
      password: ${REDIS_PASS:pass}
      lettuce:
        pool:
          enabled: true
          maxIdle: 5
          minIdle: 1
          maxActive: 5
          maxWait: 5
          timeBetweenEvictionRuns: 100000
      # jedis:
      #   pool:
      #     enabled: false
      #     maxIdle: 5
      #     minIdle: 1
      #     maxActive: 5
      #     maxWait: 5
      #     timeBetweenEvictionRuns: 100000
