server:
  netty:
    connection-timeout: 60
  tomcat:
    connection-timeout: 60
    keep-alive-timeout: 60
  port: 9092
spring:
  profiles:
    active:
      - ${ENV:dev}
  main:
    allow-bean-definition-overriding: true
  lifecycle:
    timeout-per-shutdown-phase: 10s

service:
  vault: ${VAULT_ENABLE:true}
logging:
  level:
    root: ${ROOT_LOG_LEVEL:info}
    web: ${WEB_LOG_LEVEL:debug}
    com:
      elpsykongroo:
        services:
          kafka: ${KAFKA_LOG:DEBUG}

management:
  endpoint:
    prometheus:
      enabled: true
  metrics:
    tags:
      application: ${METRICS_TAG:kafka}
  endpoints:
    web:
      exposure:
        include: ${ENDPOINTS_WEB:prometheus}