server:
  port: 9999
spring:
  servlet:
    multipart:
      max-request-size: -1
      max-file-size: -1
  lifecycle:
    timeout-per-shutdown-phase: 10s
service:
  env: ${ENV:dev}
  vault: ${VAULT_ENABLE:true}