spring:
#  cloud:
#    kubernetes:
#      discovery:
#        enabled: false
#        all-namespaces: true
#      #        master-url: https://kubernetes.default.svc
#      #      include-not-ready-addresses: true
#        discovery-server-url: ${DISCOVERY_URL}
#    discovery:
#      client:
#        health-indicator:
#          enabled: false
  #
  main:
    allow-bean-definition-overriding: true
  datasource:
    url: jdbc:mysql://${MYSQL_IP}:${MYSQL_PORT}/demo
    username: ${MYSQL_USERNAME}
    password: ${MYSQL_PASSWORD}
  redis:
    clientType: ${REDIS_TYPE}
    password: ${REDIS_PASSWORD}
    cluster:
      nodes: ${REDIS_NODE}

#    sentinel:
#      master: mymaster
#      nodes: ${REDIS_NODE}
#      password: ${REDIS_PASSWORD}
    lettuce:
      pool:
        enabled: false
        maxIdle: 5
        minIdle: 1
        maxActive: 5
        maxWait: 5
        timeBetweenEvictionRuns: 100000
    jedis:
      pool:
        enabled: true
        maxIdle: 5
        minIdle: 1
        maxActive: 5
        maxWait: 5
        timeBetweenEvictionRuns: 100000


  kafka:
    bootstrap-servers: ${KAFKA_URL:kafka.elpsykongroo.com:9094}
    security:
      protocol: ssl
#    ssl:
#      trust-store-location: ${JKS}
#      trust-store-password: ${JKS_PASS}
    consumer:
      security:
        protocol: ssl
      auto-offset-reset: earliest
#  elasticsearch:
#    rest:
#      uris:
#        - elasticsearch.elpsykongroo.com:9200
#      username: elastic
#      password: P7v84A00JsTUui436OtIn0U8
#  data:
#    elasticsearch:
#
#      client:
#        reactive:
#          endpoints: elasticsearch.elpsykongroo.com:443
#          username: elastic
#          password: P7v84A00JsTUui436OtIn0U8
#          use-ssl: true
#      repositories:
#        enabled: true
ELASTICSEARCH_URL: ${ES_URL}
ELASTICSEARCH_USER: ${ES_USER:elastic}
ELASTICSEARCH_PASS: ${ES_PASS}


