server:
  http2:
    enabled: true
  shutdown: graceful
  port: 8443

spring:
  profiles:
    active:
      - ${ENV:dev}
  application:
    name: demo
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: ${AUTH_URL:https://auth.elpsykongroo.com}/oauth2/jwks
#mybatis:
#  mapper-locations: classpath:mapper/*.xml
#  liquibase:
# change-log: classpath:liquibase/changelog/*.sql
logging:
#  log4j2:
#    config:
#      override:
#        - classpath:log4j2-spring.xml
  level:
#    org:
#      springframework:
#        web:
#          filter:
#            CommonsRequestLoggingFilter: DEBUG
    web: ${LOG_LEVEL:info}
management:
  tracing:
    enabled: ${TRACE_ENABLED:false}
---
management:
  httpexchanges:
    recording:
      enabled: ${HTTP_RECORD:false}
  endpoint:
    health:
      probes:
        enabled: true
    prometheus:
      enabled: true
    httpexchanges:
      enabled: true
  metrics:
    tags:
      application: demo
  endpoints:
    web:
      exposure:
        include: ${ENDPOINTS_WEB:health,prometheus,httpexchanges}
  zipkin:
    tracing:
      endpoint: ${ZIPKIN_HOST:http://localhost:9411/api/v2/spans}
  tracing:
    sampling:
      probability: ${TRACE_SAMPLING:1.0}

spring:
  config:
    activate:
      on-profile:
        - prod
#    import:
#      - application-prod.yaml
server:
  ssl:
    enabled: ${SSL:false}
    certificate: ${TLS_CERT}
    certificate-private-key: ${TLS_KEY}

#    key-store: ${SSL_JKS:}
#    key-store-password: ${SSL_PASS:elpsy4783}
#    key-alias: api
