server:
  http2:
    enabled: false
  shutdown: graceful
  port: 8443

spring:
  profiles:
    active:
      - ${ENV:prod}
  application:
    name: demo
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: ${AUTH_URL:https://auth.elpsykongroo.com}/oauth2/jwks
#  liquibase:
#    change-log: classpath:liquibase/changelog/*.sql
management:
  endpoint:
    health:
      probes:
        enabled: true
    prometheus:
      enabled: true
  metrics:
    export:
      prometheus:
        enabled: true
    tags:
      application: demo
  endpoints:
    web:
      exposure:
        include: prometheus, health

#  trace:
#    http:
#      enabled: true

#mybatis:
#  mapper-locations: classpath:mapper/*.xml
---
spring:
  config:
    activate:
      on-profile:
        - prod
#    import:
#      - application-prod.yaml
server:
  ssl:
    enabled: ${SSL:true}
    certificate: ${TLS_CERT}
    certificate-private-key: ${TLS_KEY}

#    key-store: ${SSL_JKS:}
#    key-store-password: ${SSL_PASS:elpsy4783}
#    key-alias: api
