server:
  port: 9201
management:
  endpoint:
    shutdown.enabled: true
  endpoints:
    web:
      exposure:
        include: ${ENDPOINTS_WEB:shutdown}
spring:
  lifecycle:
    timeout-per-shutdown-phase: 10s
  data:
    elasticsearch:        
      repositories:
        enabled: true
logging:
  level:
    root: ${ROOT_LEVEL:debug}
    web: ${WEB_LEVEL:debug}
    com:
      elpsykongroo:
        services: ${LOG_LEVEL:debug}

service:
  es:
    nodes: ${ES_URL:localhost:9200}
    user: ${ES_USER:elastic}
    pass: ${ES_PASS:elpsy}
    ssl:
      type: ${SSL_TYPE:none}
      ca: ${ES_CA_CRT:/var/ssl/es/ca.crt}
      cert: ${ES_TLS_CERT:/var/ssl/es/tls.crt}
      key: ${ES_TLS_KEY:/var/ssl/es/tls.key}
    timeout:
      connect: ${ES_CONNECT_TIME:30}
      socket: ${ES_SOCKET_TIME:30}
