server:
  port: 9201
spring:
  data:
    elasticsearch:        
      repositories:
        enabled: true
service:
  es:
    url: ${ES_URL:localhost:9200}
    user: ${ES_USER:elastic}
    pass: ${ES_PASS:elpsy}
    ssl:
      type: ${SSL_TYPE:self}
      ca: ${ES_CA_CRT:/var/ssl/es/ca.crt}
      cert: ${ES_TLS_CERT:/var/ssl/es/tls.crt}
      key: ${ES_TLS_KEY:/var/ssl/es/tls.key}
    timeout:
      connect: ${ES_CONNECT_TIME:30}
      socket: ${ES_SOCKET_TIME:30}
