management:
  endpoint:
    shutdown.enabled: true
  endpoints:
    web:
      exposure:
        include: ${ENDPOINTS_WEB:shutdown}

spring:
  lifecycle:
    timeout-per-shutdown-phase: 10s
  #  cloud:
  #    kubernetes:
  #      discovery:
  #        enabled: true
  #        all-namespaces: true
  #        #        master-url: https://kubernetes.default.svc
  #        #      include-not-ready-addresses: true
  #        discovery-server-url: ${DISCOVERY_URL}
  #    discovery:
  #      client:
  #        health-indicator:
  #          enabled: false

  main:
    allow-bean-definition-overriding: true
  kafka:
    bootstrap-servers: ${KAFKA_URL:kafka}
    security:
      protocol: ssl
    ssl:
      trust-store-location: ${JKS:jks}
      trust-store-password: ${JKS_PASS:pass}
    consumer:
      #      security:
      #        protocol: ssl
      auto-offset-reset: earliest

request:
  limit:
    global:
      tokens: ${GLOBAL_REQUEST_LIMIT:1000}
      duration: ${GLOBAL_REQUEST_DURATION:1}
      speed: ${GLOBAL_REQUEST_DURATION_SPEED:100}
    scope:
      tokens: ${REQUEST_LIMIT:100}
      duration: ${REQUEST_DURATION:1}
      speed: ${REQUEST_DURATION_SPEED:10}
  path:
    permit: ${PERMIT_PATH:/public/**}
    nonPrivate: ${PUBLIC_PATH:/public}
    limit: ${LIMIT_PATH:/}
    exclude: ${EXCLUDE_PATH:/actuator}
    filter: ${FILTER_PATH:/}
  record: 
    exclude:
      path:  ${RECORD_EXCLUDE_PATH:/actuator}
      ip:  ${RECORD_EXCLUDE_IP:ip.elpsykongroo.com}
  header:
    ip: ${IP_HEADER:x-forward-for}
    black: ${BLACK_HEADER:x-forward-for}
    white: ${WHITE_HEADER:x-forward-for}
    record: ${RECORD_HEADER:x-forward-for}
service:
  vault: ${VAULT_ENABLE:true}
  timeout:
    connect: 10
    read: 10
  ssl:
    ca:  ${CA_CRT:ca.crt}
    cert:  ${TLS_CERT:tls.crt}
    key:  ${TLS_KEY:tls.key}
  redis:
    url: ${REDIS_SERVICE:http://localhost:8379}
  auth:
    url: ${AUTH_URL:http://localhost:9000}
  storage:
    url: ${STORAGE_URL:http://localhost:9999}
  es:
    url: ${ES_URL:http://localhost:9201}
  whiteDomain: ${WHITE_DOMAIN:ip.elpsykongroo.com,localhost}
  env: ${DEPLOY_ENV:prod}