server:
  http2:
    enabled: true
  # shutdown: graceful
  port: 8443

spring:
  profiles:
    active:
      - ${ENV:prod}
  application:
    name: ${APP_NAME:demo}
  security:
    oauth2:
      client:
        registration:
          spring:
            provider: spring
            client-id: ${CLIENT_ID:spring}
            client-secret: ${CLIENT_SECRET:spring}
            authorization-grant-type: authorization_code
            redirect-uri: ${REDIRECT_URI:http://127.0.0.1:5173}
            scope: openid, profile
            client-name: spring
        provider:
          spring:
            issuer-uri: ${ISSUER_URL:http://localhost:9000}
            authorization-uri: ${AUTHORIZATION_URL:http://localhost:9000}/oauth2/authorize
            token-uri: ${AUTH_URL:http://localhost:9000}/oauth2/token
            jwk-set-uri: ${AUTH_URL:http://localhost:9000}/oauth2/jwks
      resourceserver:
        jwt:
          jwk-set-uri: ${AUTH_URL:http://localhost:9000}/oauth2/jwks
      
#mybatis:
#  mapper-locations: classpath:mapper/*.xml
#  liquibase:
# change-log: classpath:liquibase/changelog/*.sql
logging:
#  log4j2:
#    config:
#      override:
#        - classpath:log4j2-spring.xml
  level:
    org:
      springframework:
        security:
          web:
            csrf: ${CSRF_LEVEL:DEBUG}
    com:
      elpsykongroo:
        demo: ${LOG_LEVEL:INFO}
#    org:
#      springframework:
#        web:
#          filter:
#            CommonsRequestLoggingFilter: DEBUG
    web: ${LOG_LEVEL:info}
management:
  tracing:
    enabled: ${TRACE_ENABLED:true}
---
management:
  httpexchanges:
    recording:
      enabled: ${HTTP_RECORD:true}
  endpoint:
    health:
      probes:
        enabled: true
    prometheus:
      enabled: true
    httpexchanges:
      enabled: true
  metrics:
    tags:
      application: demo
  endpoints:
    web:
      exposure:
        include: ${ENDPOINTS_WEB:health,prometheus,httpexchanges}
  zipkin:
    tracing:
      endpoint: ${ZIPKIN_HOST:http://localhost:9411/api/v2/spans}
  tracing:
    sampling:
      probability: ${TRACE_SAMPLING:1.0}

spring:
  config:
    activate:
      on-profile:
        - prod
server:
  ssl:
    enabled: ${SSL:false}
    certificate: ${TLS_CERT}
    certificate-private-key: ${TLS_KEY}

#    key-store: ${SSL_JKS:}
#    key-store-password: ${SSL_PASS:password}
#    key-alias: api
