management:
  endpoint:
    shutdown.enabled: true
  endpoints:
    web:
      exposure:
        include: ${ENDPOINTS_WEB:shutdown}

spring:
  lifecycle:
    timeout-per-shutdown-phase: 10s
  #  cloud:
  #    kubernetes:
  #      discovery:
  #        enabled: true
  #        all-namespaces: true
  #        #        master-url: https://kubernetes.default.svc
  #        #      include-not-ready-addresses: true
  #        discovery-server-url: ${DISCOVERY_URL}
  #    discovery:
  #      client:
  #        health-indicator:
  #          enabled: false

  main:
    allow-bean-definition-overriding: true
  kafka:
    bootstrap-servers: ${KAFKA_URL:kafka}
    security:
      protocol: ssl
    ssl:
      trust-store-location: ${JKS:jks}
      trust-store-password: ${JKS_PASS:pass}
    consumer:
      #      security:
      #        protocol: ssl
      auto-offset-reset: earliest
service:
  vault: ${VAULT_ENABLE:true}
  ssl:
    ca:  ${CA_CRT:ca.crt}
    cert:  ${TLS_CERT:tls.crt}
    key:  ${TLS_KEY:tls.key}
