server:
  port: 9000

spring:
  jpa:
#    defer-datasource-initialization: true
    open-in-view: false
    properties:
       hibernate:
         dialect: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: update
      # naming:
      #   implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyJpaCompliantImpl
  #   database-platform: org.hibernate.dialect.MySQL8Dialect

  liquibase:
    enabled: true
    change-log: classpath:liquibase/changelog.xml
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://${MYSQL_IP:localhost}:${MYSQL_PORT:13306}/auth?useUnicode=true&characterEncoding=UTF-8
    username: ${MYSQL_USER:root}
    password: ${MYSQL_PASS:elpsy}
  security:
    oauth2:
      client:
        registration:
          google-idp:
            provider: google
            client-id: ${GOOGLE_CLIENT_ID:google-client-id}
            client-secret: ${GOOGLE_CLIENT_SECRET:google-client-secret}
            scope: openid, https://www.googleapis.com/auth/userinfo.profile, https://www.googleapis.com/auth/userinfo.email
            client-name: Sign in with Google
          github-idp:
            provider: github
            client-id: ${GITHUB_CLIENT_ID:client-id}
            client-secret: ${GITHUB_CLIENT_SECRET:client-secret}
            scope: user:email, read:user
            client-name: Sign in with GitHub
        provider:
          spring:
            issuer-uri: ${AUTH_URL:http://192.168.1.106:9000}
            authorization-uri: ${AUTH_URL:http://localhost:9000}/oauth2/authorize
            token-uri: ${AUTH_URL:http://localhost:9000}/oauth2/token
            jwk-set-uri: ${AUTH_URL:http://localhost:9000}/oauth2/jwks
          google:
            user-name-attribute: email
          github:
            user-name-attribute: login

logging:
  level:
    root: ${LOG_LEVEL:INFO}  
    # org.springframework.web: INFO
    # org.springframework.security: INFO
    # org.springframework.security.oauth2: INFO
#    org.springframework.boot.autoconfigure: DEBUG
