server:
  port: 9000

spring:
  jpa:
    # open-in-view: true
    # properties:
    #   hibernate:
    hibernate:
      ddl-auto: update
      # naming:
      #   implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyJpaCompliantImpl
  #   database-platform: org.hibernate.dialect.MySQL8Dialect

  liquibase:
    enabled: false
    change-log: classpath:liquibase/changelog.xml
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://${MYSQL_IP:localhost}:${MYSQL_PORT:13306}/auth?useUnicode=true&characterEncoding=UTF-8
    username: root
    password: elpsy
  security:
    oauth2:
      client:
        registration:
          google-idp:
            provider: google
            client-id: ${GOOGLE_CLIENT_ID:google-client-id}
            client-secret: ${GOOGLE_CLIENT_SECRET:google-client-secret}
            scope: openid, https://www.googleapis.com/auth/userinfo.profile, https://www.googleapis.com/auth/userinfo.email
            client-name: Sign in with Google
          github-idp:
            provider: github
            client-id: ${GITHUB_CLIENT_ID:8f481b019dd9c4a0c6e5}
            client-secret: ${GITHUB_CLIENT_SECRET:1cb3b5cd59f856c6226298de81959d12c2085031}
            scope: user:email, read:user
            client-name: Sign in with GitHub
        provider:
          spring:
#            issuer-uri: ${AUTH_URL:http://localhost:9000}
            authorization-uri: ${AUTH_URL:http://localhost:9000}/oauth2/authorize
            token-uri: ${AUTH_URL:http://localhost:9000}/oauth2/token
            jwk-set-uri: ${AUTH_URL:http://localhost:9000}/oauth2/jwks
          google:
            user-name-attribute: email
          github:
            user-name-attribute: login

logging:
  level:
    root: INFO  
    # org.springframework.web: INFO
    # org.springframework.security: INFO
    # org.springframework.security.oauth2: INFO
#    org.springframework.boot.autoconfigure: DEBUG
