CREATE TABLE "authorization" (
   id VARCHAR(255) NOT NULL,
   registered_client_id VARCHAR(255),
   principal_name VARCHAR(255),
   authorization_grant_type VARCHAR(255),
   authorized_scopes VARCHAR(1000),
   attributes VARCHAR(4000),
   state VARCHAR(500),
   authorization_code_value VARCHAR(1000),
   authorization_code_issued_at TIMESTAMP WITHOUT TIME ZONE,
   authorization_code_expires_at TIMESTAMP WITHOUT TIME ZONE,
   authorization_code_metadata VARCHAR(255),
   access_token_value VARCHAR(1000),
   access_token_issued_at TIMESTAMP WITHOUT TIME ZONE,
   access_token_expires_at TIMESTAMP WITHOUT TIME ZONE,
   access_token_metadata VARCHAR(1000),
   access_token_type VARCHAR(255),
   access_token_scopes VARCHAR(1000),
   refresh_token_value VARCHAR(1000),
   refresh_token_issued_at TIMESTAMP WITHOUT TIME ZONE,
   refresh_token_expires_at TIMESTAMP WITHOUT TIME ZONE,
   refresh_token_metadata VARCHAR(1000),
   oidc_id_token_value VARCHAR(1000),
   oidc_id_token_issued_at TIMESTAMP WITHOUT TIME ZONE,
   oidc_id_token_expires_at TIMESTAMP WITHOUT TIME ZONE,
   oidc_id_token_metadata VARCHAR(1000),
   oidc_id_token_claims VARCHAR(1000),
   CONSTRAINT pk_authorization PRIMARY KEY (id)
);