server:
  netty:
    connection-timeout: -1
  tomcat:
    connection-timeout: -1
    keep-alive-timeout: -1
  port: 9999
spring:
  profiles:
    active:
      - ${ENV:dev}
  main:
    allow-bean-definition-overriding: true
  servlet:
    multipart:
      max-request-size: -1
      max-file-size: -1
      resolve-lazily: true
  lifecycle:
    timeout-per-shutdown-phase: 10s
service:
  vault: ${VAULT_ENABLE:true}
logging:
  level:
    root: info
    web: debug
    com:
      elpsykongroo:
        storage: debug