spring:
  kafka:
    bootstrap-servers: ${KAFKA_URL:broker.elpsykongroo.com:443}
    security:
      protocol: SSL
    ssl:
      trust-store-type: PEM
      trust-store-location: ${SSL_PEM:classpath:/ssl.pem}
    admin:
      security:
        protocol: SSL
      ssl:
        trust-store-type: PEM
        trust-store-location: ${SSL_PEM:classpath:/ssl.pem}
    consumer:
      enable-auto-commit: true
      auto-offset-reset: earliest
    #      auto-commit-interval: 500
    #      value-deserializer: org.apache.kafka.common.serialization.ByteArraySerializer
      security:
        protocol: SSL
      ssl:
        trust-store-type: PEM
        trust-store-location: ${SSL_PEM:classpath:/ssl.pem}
    producer:
      value-serializer: org.apache.kafka.common.serialization.ByteArraySerializer
    properties:
      max:
        request:
          size: 10000000