spring:
  kafka:
    bootstrap-servers: ${KAFKA_URL:broker.elpsykongroo.com:443}
    security:
      protocol: SSL
    ssl:
      trust-store-type: JKS
      trust-store-location: ${JKS:file:/var/secret/truststore.jks}
      trust-store-password: ${JKS_PASS:pass}
    admin:
      security:
        protocol: SSL
      ssl:
        trust-store-type: JKS
        trust-store-location: ${JKS:file:/var/secret/truststore.jks}
        trust-store-password: ${JKS_PASS:pass}
    consumer:
      enable-auto-commit: false
      auto-offset-reset: earliest
    #      value-deserializer: org.apache.kafka.common.serialization.ByteArraySerializer
      security:
        protocol: SSL
      ssl:
        trust-store-type: JKS
        trust-store-location: ${JKS:file:/var/secret/truststore.jks}
        trust-store-password: ${JKS_PASS:pass}
    producer:
      value-serializer: org.apache.kafka.common.serialization.ByteArraySerializer
    listener:
      immediate-stop: true
      ack-mode: MANUAL_IMMEDIATE
      async-acks: true
    properties:
      max:
        request:
          size: 10000000