name: Just build (native)
on: 
  workflow_dispatch:
    inputs:
      environment:
        description: 'Environment to run the workflow against'
        type: environment
        required: true
jobs:
  build:
    uses: Labman4/workflow/.github/workflows/build-native-image.yml@native-image
