name: Native builder
on: 
  workflow_dispatch:
    inputs:
      environment:
        description: 'Environment to run the workflow against'
        type: environment
        required: true
jobs:
  pre-build:
    uses: Labman4/workflow/.github/workflows/pre-build.yml@native-image
