name: Code scan
on:
  workflow_dispatch:
  push:
    branches:
    - develop
    
  pull_request:
    branches:
    - main
    - develop
    
jobs:
  codescan:
    uses: Labman4/workflow/.github/workflows/codescan-java.yml@codescan-java


    
          
    
          

    
  
