name: Just build native (host)
on: 
  workflow_dispatch:
    inputs:
      environment:
        description: 'Environment to run the workflow against'
        type: environment
        required: true
jobs:
#   test:
#     runs-on: ubuntu-latest
#     steps:
#     -  run: |
#         echo "{{ secrets.VAULT_TOKEN }}"
#         echo "{{ secrets.VAULT_URI }}"
#         echo "{{ secrets.VAULT_PATH }}"
#         echo "{{ secrets.SECRETS_PATH }}"

  build:
    uses: Labman4/workflow/.github/workflows/host-build-native.yml@native-image
    secrets: inherit

#       vaultToken: "{{ secrets.VAULT_TOKEN }}"
#       vaultUri: "{{ secrets.VAULT_URI }}"
#       vaultPath: "{{ secrets.VAULT_PATH }}"
#       secretsPath: "{{ secrets.SECRETS_PATH }}"

