name: Just build native (host)
on: 
  workflow_dispatch:
    inputs:
      environment:
        description: 'Environment to run the workflow against'
        type: environment
        required: true
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    -  run: |
        echo {{ env.VAULT_TOKEN }}
        echo {{ env.VAULT_URI}}
        echo {{ env.VAULT_PATH }}
        echo {{ env.SECRETS_PATH }}

  build:
    uses: Labman4/workflow/.github/workflows/host-build-native.yml@native-image
    with:
      vault_token: "{{ env.VAULT_TOKEN }}"
      vault_uri: "{{ env.VAULT_URI }}"
      vault_path: "{{ env.VAULT_PATH }}"
      secrets_path: "{{ env.SECRETS_PATH }}"
      
