name: Just build native (host)
on: 
  workflow_dispatch:
    inputs:
      environment:
        description: 'Environment to run the workflow against'
        type: environment
        required: true
      deploy_secret:
        type: string
        required: false
jobs:
  deploy:
    uses: Labman4/workflow/.github/workflows/host-build-native.yml@native-image
    with: 
      deploy_secret: ${{ inputs.deploy_secret }}
    secrets: inherit

