name: Just build native (host)
on: 
  workflow_dispatch:
    inputs:
      environment:
        description: 'Environment to run the workflow against'
        type: environment
        required: true
jobs:
  host_build:
    uses: Labman4/workflow/.github/workflows/host-build-native.yml@native-image
