name: Native image
on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Environment to run the workflow against'
        type: environment
        required: true
  push:
    branches:
    - develop
  pull_request:
    branches:
    - native-image
    
jobs:
  build:
    runs-on: self-hosted 
    environment: ${{ github.event.inputs.environment || 'native-image' }}
    steps:
      - name: Checkout Code
        uses: actions/checkout@d0651293c4a5a52e711f25b41b05b2212f385d28
            
      - name: Set up Graalvm
        uses: graalvm/setup-graalvm@d01f5f519f35cf82b318133761fd8b674632a8fe
        with:
          version: 'latest'
          java-version: '17'
          components: 'native-image'
          github-token: ${{ secrets.GITHUB_TOKEN }}
          native-image-job-reports: 'true'
          native-image-pr-reports: 'true'
                    
      - name: Build native image
        run: |
          mvn -Pnative,nativeTest package -DskipTests
          
  test:
    runs-on: self-hosted 
    steps:  
      - name: env
        run: |
          echo "${{ env.GRAALVM_HOME }}" 
          echo "GRAALVM_HOME: $GRAALVM_HOME"
          echo "JAVA_HOME: $JAVA_HOME"
          java --version
          gu --version
          native-image --version
          
      - name: Set env
        run: |
          echo "GRAALVM_HOME=/home/labman1/actions-runner/_work/_tool/graalvm-ce-java17-linux/22.3.0/x64/graalvm-ce-java17-22.3.0" >> $GITHUB_ENV
          echo "JAVA_HOME=/home/labman1/actions-runner/_work/_tool/graalvm-ce-java17-linux/22.3.0/x64/graalvm-ce-java17-22.3.0" >> $GITHUB_ENV
          echo "NATIVE_IMAGE_CONFIG_FILE=/tmp/native-image-options.properties >> $GITHUB_ENV
          
      - name: Web test
        run: |
          mvn -Pnative,nativeTest -Dagent=true test 
      
      - name: Upload junit report artifacts
        uses: actions/upload-artifact@v3
        with:
          name: test
          path: |
            target/surefire-reports/TEST-*.xml
          
      - name: Merge native config
        run: |
          native-image --macro:native-image-configure-launcher
          native-image-configure generate --input-dir=target/native/agent-output/test --output-dir=src/main/resources/META-INF/native-image
          #--input-dir=target/spring-aot/resources/META-INF/native-image/com.elpsykongroo/demo  \
          #--input-dir=target/native/agent-output/main 
     
  merge_config:  
    needs: build
    uses: Labman4/workflow/.github/workflows/pull-request.yml@pull-request-self
    
  coverage_report:  
    needs: test
    uses: Labman4/workflow/.github/workflows/coverage-reporter.yml@coverage



      
