name: Native image
on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Environment to run the workflow against'
        type: environment
        required: true
  push:
    branches:
    - develop
    - native-image
    
  pull_request:
    branches:
    - native-image
    
jobs:
  native:
    uses: Labman4/workflow/.github/workflows/native-image.yml@native-image
    with:
      configuration-path: .github/labeler.yml
 

    
          
    
          

    
  
