name: Prepare build (storage)
on:
  workflow_dispatch:
  pull_request:
    branches:
    - main 
  push:
    branches:
    - native-image
    paths-ignore:
      - .github/**
    paths:
      -  'storage/storage-server/**'
jobs:
  native:
    uses: Labman4/workflow/.github/workflows/native-image-storage.yml@native-image
    secrets: inherit
 

    
          
    
          

    
  
