name: Prepare build (gateway)
on:
  workflow_dispatch:
  pull_request:
    branches:
    - main 
  push:
    paths:
      - gateway/**   
      - base/**	

jobs:
  build:
    uses: Labman4/workflow/.github/workflows/native-image-gateway.yml@native-image
    secrets: inherit
    with: 
      module: gateway
      version: 0.0.2
      native: true
      secretPath: kv/app/native/gateway
      
 

    
          
    
          

    
  
