name: Prepare build (storage)
on:
  workflow_dispatch:
  pull_request:
    branches:
    - main 
  push:
    branches:
    - native-image
    paths:
      -  'storage/storage-server/**'
      -  'pom.xml'
jobs:
  build: 
    uses: Labman4/workflow/.github/workflows/buildpacks.yml@buildpacks
    secrets: inherit
    with:
      module: storage
      moduleName: storage-server
      version: dev

  native:
    uses: Labman4/workflow/.github/workflows/native-image-base.yml@native-image
    secrets: inherit
    with:
      module: storage
      moduleName: storage-server
      version: 0.0.1
      
      
 

    
          
    
          

    
  
