name: Prepare build (gateway)
on:
  workflow_dispatch:
  pull_request:
    branches:
    - main 
  push:
    branches:
    - native-image
    paths:
      - gateway/**   
      - 'pom.xml'

jobs:
  build: 
    uses: Labman4/workflow/.github/workflows/buildpacks.yml@buildpacks
    secrets: inherit
    with:
      module: gateway
      version: dev
  native:
    uses: Labman4/workflow/.github/workflows/native-image.yml@native-image
    secrets: inherit
    with: 
      module: gateway
      version: 0.0.2
 

    
          
    
          

    
  
