name: Prepare build (search)
on:
  workflow_dispatch:
  pull_request:
    branches:
    - main 
  push:
    branches:
    - native-image
    paths:
      -  'elasticsearch/**'
jobs:
  build:
    uses: Labman4/workflow/.github/workflows/buildpacks.yml@buildpacks
    secrets: inherit
    with:
      module: elasticsearch
      version: 1.0.0
      env: dev
  pre-build:
    uses: Labman4/workflow/.github/workflows/buildpacks-native.yml@buildpacks
    secrets: inherit
    with:
      module: elasticsearch
      mode: pre
  native:
    uses: Labman4/workflow/.github/workflows/native-image-elasticsearch.yml@native-image
    secrets: inherit
    with:
      module: elasticsearch
      version: 1.0.0
