name: Prepare build (auth)
on:
  workflow_dispatch:
  pull_request:
    branches:
    - main 
  push:
    branches:
    - native-image
    paths:
      -  '**/*authorization-server/**'
jobs:
  build:
    uses: Labman4/workflow/.github/workflows/buildpacks.yml@buildpacks
    secrets: inherit
    with:
      module: auth
      moduleName: authorization-server
      version: dev
      env: dev
  native:
    uses: Labman4/workflow/.github/workflows/native-image-base.yml@native-image
    secrets: inherit
    with:
      module: auth
      moduleName: authorization-server
      version: 0.0.2
      
      
 

    
          
    
          

    
  
