name: Prepare build (redis)
on:
  workflow_dispatch:
  pull_request:
    branches:
    - main 
  push:
    branches:
    - native-image
    paths:
      -  'redis/redis-server/**'
jobs:
  native:
    uses: Labman4/workflow/.github/workflows/native-image-base.yml@native-image
    secrets: inherit
    with:
      module: redis
      moduleName: redis-server
      version: 0.0.1
      
      
 

    
          
    
          

    
  
