name: Prepare build (kafka)
on:
  workflow_dispatch:
  pull_request:
    branches:
    - main 
  push:
    branches:
    - native-image
    paths:
      -  'kafka/**'
jobs:
  build: 
    uses: Labman4/workflow/.github/workflows/buildpacks.yml@buildpacks
    secrets: inherit
    with:
      module: kafka
      version: 0.0.1
      env: dev
  native:
    uses: Labman4/workflow/.github/workflows/native-image-base.yml@native-image
    secrets: inherit
    with:
      module: kafka
      version: 0.0.1
