name: Prepare build (kafka)
on:
  workflow_dispatch:
  pull_request:
    branches:
    - main 
  push:
    paths:
      -  'kafka/**'
jobs:
  build:
    uses: Labman4/workflow/.github/workflows/native-image-kafka.yml@native-image
    secrets: inherit
    with:
      module: kafka
      version: 0.0.1
      native: true
      secretPath: kv/app/native/kafka
