name: Prepare build (redis)
on:
  workflow_dispatch:
  pull_request:
    branches:
    - main 
  push:
    branches-ignore:
      - main
    paths:
      -  'redis/**'
jobs:   
  build:
    uses: Labman4/workflow/.github/workflows/native-image-redis.yml@native-image
    secrets: inherit
    with:
      module: redis
      version: 0.0.1
      native: true
      secretPath: kv/app/native/redis
      
      
 

    
          
    
          

    
  
