name: Prepare build (native)
on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Environment to run the workflow against'
        type: environment
        required: true
  pull_request:
    branches:
    - main 
jobs:
  native:
    uses: Labman4/workflow/.github/workflows/native-image.yml@native-image
    secrets: inherit
 

    
          
    
          

    
  
