name: Prepare build (search)
on:
  workflow_dispatch:
  pull_request:
    branches:
    - main 
  push:
    branches:
    - native-image
    paths:
      -  'elasticsearch/elasticsearch-server/**'
      -  'pom.xml'

jobs:
  build:
    uses: Labman4/workflow/.github/workflows/buildpacks.yml@buildpacks
    secrets: inherit
    with:
      module: elasticsearch
      moduleName: elasticsearch-server
      version: 0.0.1
      env: dev
  pre-build:
    uses: Labman4/workflow/.github/workflows/buildpacks-native.yml@buildpacks
    secrets: inherit
    with:
      module: elasticsearch
      moduleName: elasticsearch-server
#   native:
#     uses: Labman4/workflow/.github/workflows/native-image-base.yml@native-image
#     secrets: inherit
#     with:
#       module: elasticsearch
#       moduleName: elasticsearch-server
#       version: 0.0.1
