name: Prepare build (auth)
on:
  workflow_dispatch:
  pull_request:
    branches:
    - main 
  push:
    paths:
      -  'auth/**'
jobs:
  build:
    uses: Labman4/workflow/.github/workflows/native-image-postgres.yml@native-image
    secrets: inherit
    with:
      module: auth
      version: 0.0.2
      secretPath: kv/app/native/auth
      native: true
      
      
 

    
          
    
          

    
  
