name: Prepare build (storage)
on:
  workflow_dispatch:
  pull_request:
    branches:
    - main 
  push:
    branches-ignore:
      - main
    paths:
      -  'storage/**'
jobs:
  build:
    uses: Labman4/workflow/.github/workflows/native-image-base.yml@native-image
    secrets: inherit
    with:
      module: storage
      version: 1.0.0
      native: true
      secretPath: kv/app/native/storage
      
      
 

    
          
    
          

    
  
