name: Prepare build (message)
on:
  workflow_dispatch:
#  pull_request:
#    branches:
#      - main
#    paths:
#      - message/**
  push:
    branches-ignore:
      - main
    paths:
      - message/**   
jobs:
  build:
    uses: Labman4/workflow/.github/workflows/native-image-base.yml@native-image
    secrets: inherit
    with: 
      module: message
      version: 0.0.1
      native: true
      secretPath: kv/app/native/message
      
 

    
          
    
          

    
  
