name: release
on: 
  workflow_dispatch:
#     inputs:
#       deploy_secret:
#         type: string
#         required: false

jobs:
  build:
    uses: Labman4/workflow/.github/workflows/deploy.yml@deploy
