server:
  port: 8379
logging:
  level:
    root: ${ROOT_LOG_LEVEL:info}
    web: ${WEB_LOG_LEVEL:debug}
    com:
      elpsykongroo:
        services:
          redis: ${REDIS_LOG_LEVEL:debug}
#spring:
#  data:
#    redis:
#      cluster:
#        -  ${REDIS_NODES:redis-cluster.redis.svc:6379}
#      lettuce:
#        pool:
#          enabled: true
service:
  vault: ${VAULT_ENABLE:true}
